// GENERATED by tools/derive-modules.mjs from ep01Write
import { ep01Write, ep01Derive } from "./ep01Write";
import { carousel } from "./studio/derive";
export const ep01Carousel = carousel("ep01Carousel", ep01Write, ep01Derive, {
  title: ["Write in Markdown.", "See it rendered."],
  hi: "rendered",
});
