// GENERATED by tools/derive-modules.mjs from ep01Write
import { ep01Write, ep01Derive } from "./ep01Write";
import { single } from "./studio/derive";
export const ep01Single = single("ep01Single", ep01Write, ep01Derive);
