// GENERATED by tools/derive-modules.mjs from ep01Write
import { ep01Write, ep01Derive } from "./ep01Write";
import { verticalCut } from "./studio/derive";
export const ep01Vertical = verticalCut("ep01Vertical", ep01Write, ep01Derive);
