// GENERATED by tools/derive-modules.mjs from ep02Folder
import { ep02Folder, ep02Derive } from "./ep02Folder";
import { carousel } from "./studio/derive";
export const ep02Carousel = carousel("ep02Carousel", ep02Folder, ep02Derive, { title: ["One folder.","Every way out","stays open."], hi: "open" });
