// GENERATED by tools/derive-modules.mjs from ep02Folder
import { ep02Folder, ep02Derive } from "./ep02Folder";
import { single } from "./studio/derive";
export const ep02Single = single("ep02Single", ep02Folder, ep02Derive);
