// GENERATED by tools/derive-modules.mjs from ep02Folder
import { ep02Folder, ep02Derive } from "./ep02Folder";
import { verticalCut } from "./studio/derive";
export const ep02Vertical = verticalCut("ep02Vertical", ep02Folder, ep02Derive);
