// GENERATED by tools/derive-modules.mjs from ep03Habits
import { ep03Habits, ep03Derive } from "./ep03Habits";
import { single } from "./studio/derive";
export const ep03Single = single("ep03Single", ep03Habits, ep03Derive);
