// GENERATED by tools/derive-modules.mjs from ep03Habits
import { ep03Habits, ep03Derive } from "./ep03Habits";
import { verticalCut } from "./studio/derive";
export const ep03Vertical = verticalCut("ep03Vertical", ep03Habits, ep03Derive);
