// GENERATED by tools/derive-modules.mjs from ep03Habits
import { ep03Habits, ep03Derive } from "./ep03Habits";
import { carousel } from "./studio/derive";
export const ep03Carousel = carousel("ep03Carousel", ep03Habits, ep03Derive, {
  title: ["Small habits.", "Big calm."],
  hi: "calm",
});
