// GENERATED by tools/derive-modules.mjs from ep04Yours
import { ep04Yours, ep04Derive } from "./ep04Yours";
import { verticalCut } from "./studio/derive";
export const ep04Vertical = verticalCut("ep04Vertical", ep04Yours, ep04Derive);
