// GENERATED by tools/derive-modules.mjs from ep04Yours
import { ep04Yours, ep04Derive } from "./ep04Yours";
import { carousel } from "./studio/derive";
export const ep04Carousel = carousel("ep04Carousel", ep04Yours, ep04Derive, { title: ["Make it yours."], hi: "yours" });
