// GENERATED by tools/derive-modules.mjs from ep04Yours
import { ep04Yours, ep04Derive } from "./ep04Yours";
import { single } from "./studio/derive";
export const ep04Single = single("ep04Single", ep04Yours, ep04Derive);
