// GENERATED by tools/derive-modules.mjs from ep05Librarian
import { ep05Librarian, ep05Derive } from "./ep05Librarian";
import { verticalCut } from "./studio/derive";
export const ep05Vertical = verticalCut("ep05Vertical", ep05Librarian, ep05Derive);
