// GENERATED by tools/derive-modules.mjs from ep05Librarian
import { ep05Librarian, ep05Derive } from "./ep05Librarian";
import { carousel } from "./studio/derive";
export const ep05Carousel = carousel("ep05Carousel", ep05Librarian, ep05Derive, {
  title: ["A Librarian that files,", "never rewrites."],
  hi: "rewrites",
});
