// GENERATED by tools/derive-modules.mjs from ep05Librarian
import { ep05Librarian, ep05Derive } from "./ep05Librarian";
import { single } from "./studio/derive";
export const ep05Single = single("ep05Single", ep05Librarian, ep05Derive);
