// GENERATED by tools/derive-modules.mjs from ep06Chat
import { ep06Chat, ep06Derive } from "./ep06Chat";
import { carousel } from "./studio/derive";
export const ep06Carousel = carousel("ep06Carousel", ep06Chat, ep06Derive, { title: ["Ask your notes."], hi: "notes" });
