// GENERATED by tools/derive-modules.mjs from ep06Chat
import { ep06Chat, ep06Derive } from "./ep06Chat";
import { verticalCut } from "./studio/derive";
export const ep06Vertical = verticalCut("ep06Vertical", ep06Chat, ep06Derive);
