// GENERATED by tools/derive-modules.mjs from ep06Chat
import { ep06Chat, ep06Derive } from "./ep06Chat";
import { single } from "./studio/derive";
export const ep06Single = single("ep06Single", ep06Chat, ep06Derive);
