// GENERATED by tools/derive-modules.mjs from ep07Secure
import { ep07Secure, ep07Derive } from "./ep07Secure";
import { verticalCut } from "./studio/derive";
export const ep07Vertical = verticalCut("ep07Vertical", ep07Secure, ep07Derive);
