// GENERATED by tools/derive-modules.mjs from ep07Secure
import { ep07Secure, ep07Derive } from "./ep07Secure";
import { single } from "./studio/derive";
export const ep07Single = single("ep07Single", ep07Secure, ep07Derive);
