// GENERATED by tools/derive-modules.mjs from ep07Secure
import { ep07Secure, ep07Derive } from "./ep07Secure";
import { carousel } from "./studio/derive";
export const ep07Carousel = carousel("ep07Carousel", ep07Secure, ep07Derive, {
  title: ["AI is invited in.", "It does not own", "the house."],
  hi: "house",
});
