// GENERATED by tools/derive-modules.mjs from ep08Web
import { ep08Web, ep08Derive } from "./ep08Web";
import { carousel } from "./studio/derive";
export const ep08Carousel = carousel("ep08Carousel", ep08Web, ep08Derive, { title: ["Your folder,","in your browser."], hi: "browser" });
