// GENERATED by tools/derive-modules.mjs from ep08Web
import { ep08Web, ep08Derive } from "./ep08Web";
import { verticalCut } from "./studio/derive";
export const ep08Vertical = verticalCut("ep08Vertical", ep08Web, ep08Derive);
