// GENERATED by tools/derive-modules.mjs from ep08Web
import { ep08Web, ep08Derive } from "./ep08Web";
import { single } from "./studio/derive";
export const ep08Single = single("ep08Single", ep08Web, ep08Derive);
