// GENERATED by tools/derive-modules.mjs from s01e05LighthouseKeeper
import { s01e05LighthouseKeeper, s01e05Derive } from "./s01e05LighthouseKeeper";
import { verticalCut } from "./studio/derive";
export const s01e05Vertical = verticalCut("s01e05Vertical", s01e05LighthouseKeeper, s01e05Derive);
