// GENERATED by tools/derive-modules.mjs from s01e04Burrow
import { s01e04Burrow, s01e04Derive } from "./s01e04Burrow";
import { carousel } from "./studio/derive";
export const s01e04Carousel = carousel("s01e04Carousel", s01e04Burrow, s01e04Derive, {
  title: ["The burrow."],
  hi: "burrow",
});
