// GENERATED by tools/derive-modules.mjs from s01e06Threads
import { s01e06Threads, s01e06Derive } from "./s01e06Threads";
import { single } from "./studio/derive";
export const s01e06Single = single("s01e06Single", s01e06Threads, s01e06Derive);
