// GENERATED by tools/derive-modules.mjs from s01e10Seasons
import { s01e10Seasons, s01e10Derive } from "./s01e10Seasons";
import { verticalCut } from "./studio/derive";
export const s01e10Vertical = verticalCut("s01e10Vertical", s01e10Seasons, s01e10Derive);
