// GENERATED by tools/derive-modules.mjs from s01e04Burrow
import { s01e04Burrow, s01e04Derive } from "./s01e04Burrow";
import { verticalCut } from "./studio/derive";
export const s01e04Vertical = verticalCut("s01e04Vertical", s01e04Burrow, s01e04Derive);
