// GENERATED by tools/derive-modules.mjs from s01e08LockedBox
import { s01e08LockedBox, s01e08Derive } from "./s01e08LockedBox";
import { verticalCut } from "./studio/derive";
export const s01e08Vertical = verticalCut("s01e08Vertical", s01e08LockedBox, s01e08Derive);
