// GENERATED by tools/derive-modules.mjs from s01e07AskTheIsland
import { s01e07AskTheIsland, s01e07Derive } from "./s01e07AskTheIsland";
import { single } from "./studio/derive";
export const s01e07Single = single("s01e07Single", s01e07AskTheIsland, s01e07Derive);
