// GENERATED by tools/derive-modules.mjs from s01e09OtherShores
import { s01e09OtherShores, s01e09Derive } from "./s01e09OtherShores";
import { carousel } from "./studio/derive";
export const s01e09Carousel = carousel("s01e09Carousel", s01e09OtherShores, s01e09Derive, { title: ["Other shores."], hi: "shores" });
