// GENERATED by tools/derive-modules.mjs from s01e04Burrow
import { s01e04Burrow, s01e04Derive } from "./s01e04Burrow";
import { single } from "./studio/derive";
export const s01e04Single = single("s01e04Single", s01e04Burrow, s01e04Derive);
