// GENERATED by tools/derive-modules.mjs from s01e07AskTheIsland
import { s01e07AskTheIsland, s01e07Derive } from "./s01e07AskTheIsland";
import { verticalCut } from "./studio/derive";
export const s01e07Vertical = verticalCut("s01e07Vertical", s01e07AskTheIsland, s01e07Derive);
