// GENERATED by tools/derive-modules.mjs from s01e02PlainWords
import { s01e02PlainWords, s01e02Derive } from "./s01e02PlainWords";
import { carousel } from "./studio/derive";
export const s01e02Carousel = carousel("s01e02Carousel", s01e02PlainWords, s01e02Derive, { title: ["Plain words."], hi: "words" });
