// GENERATED by tools/derive-modules.mjs from s01e01Arrival
import { s01e01Arrival, s01e01Derive } from "./s01e01Arrival";
import { single } from "./studio/derive";
export const s01e01Single = single("s01e01Single", s01e01Arrival, s01e01Derive);
