// GENERATED by tools/derive-modules.mjs from s01e05LighthouseKeeper
import { s01e05LighthouseKeeper, s01e05Derive } from "./s01e05LighthouseKeeper";
import { single } from "./studio/derive";
export const s01e05Single = single("s01e05Single", s01e05LighthouseKeeper, s01e05Derive);
