// GENERATED by tools/derive-modules.mjs from s01e05LighthouseKeeper
import { s01e05LighthouseKeeper, s01e05Derive } from "./s01e05LighthouseKeeper";
import { carousel } from "./studio/derive";
export const s01e05Carousel = carousel("s01e05Carousel", s01e05LighthouseKeeper, s01e05Derive, {
  title: ["The lighthouse", "keeper."],
  hi: "keeper",
});
