// GENERATED by tools/derive-modules.mjs from s01e03Workshop
import { s01e03Workshop, s01e03Derive } from "./s01e03Workshop";
import { single } from "./studio/derive";
export const s01e03Single = single("s01e03Single", s01e03Workshop, s01e03Derive);
