// GENERATED by tools/derive-modules.mjs from s01e10Seasons
import { s01e10Seasons, s01e10Derive } from "./s01e10Seasons";
import { carousel } from "./studio/derive";
export const s01e10Carousel = carousel("s01e10Carousel", s01e10Seasons, s01e10Derive, {
  title: ["Seasons."],
  hi: "Seasons",
});
