// GENERATED by tools/derive-modules.mjs from s01e09OtherShores
import { s01e09OtherShores, s01e09Derive } from "./s01e09OtherShores";
import { single } from "./studio/derive";
export const s01e09Single = single("s01e09Single", s01e09OtherShores, s01e09Derive);
