// GENERATED by tools/derive-modules.mjs from s01e10Seasons
import { s01e10Seasons, s01e10Derive } from "./s01e10Seasons";
import { single } from "./studio/derive";
export const s01e10Single = single("s01e10Single", s01e10Seasons, s01e10Derive);
