// GENERATED by tools/derive-modules.mjs from s01e03Workshop
import { s01e03Workshop, s01e03Derive } from "./s01e03Workshop";
import { carousel } from "./studio/derive";
export const s01e03Carousel = carousel("s01e03Carousel", s01e03Workshop, s01e03Derive, { title: ["The workshop."], hi: "workshop" });
