// GENERATED by tools/derive-modules.mjs from s01e08LockedBox
import { s01e08LockedBox, s01e08Derive } from "./s01e08LockedBox";
import { carousel } from "./studio/derive";
export const s01e08Carousel = carousel("s01e08Carousel", s01e08LockedBox, s01e08Derive, { title: ["The locked box."], hi: "box" });
