// GENERATED by tools/derive-modules.mjs from s01e08LockedBox
import { s01e08LockedBox, s01e08Derive } from "./s01e08LockedBox";
import { single } from "./studio/derive";
export const s01e08Single = single("s01e08Single", s01e08LockedBox, s01e08Derive);
