// GENERATED by tools/derive-modules.mjs from s01e01Arrival
import { s01e01Arrival, s01e01Derive } from "./s01e01Arrival";
import { carousel } from "./studio/derive";
export const s01e01Carousel = carousel("s01e01Carousel", s01e01Arrival, s01e01Derive, {
  title: ["Arrival."],
  hi: "Arrival",
});
