// GENERATED by tools/derive-modules.mjs from s01e09OtherShores
import { s01e09OtherShores, s01e09Derive } from "./s01e09OtherShores";
import { verticalCut } from "./studio/derive";
export const s01e09Vertical = verticalCut("s01e09Vertical", s01e09OtherShores, s01e09Derive);
