// GENERATED by tools/derive-modules.mjs from s01e03Workshop
import { s01e03Workshop, s01e03Derive } from "./s01e03Workshop";
import { verticalCut } from "./studio/derive";
export const s01e03Vertical = verticalCut("s01e03Vertical", s01e03Workshop, s01e03Derive);
