// GENERATED by tools/derive-modules.mjs from s01e06Threads
import { s01e06Threads, s01e06Derive } from "./s01e06Threads";
import { carousel } from "./studio/derive";
export const s01e06Carousel = carousel("s01e06Carousel", s01e06Threads, s01e06Derive, { title: ["Threads."], hi: "Threads" });
