// GENERATED by tools/derive-modules.mjs from s01e07AskTheIsland
import { s01e07AskTheIsland, s01e07Derive } from "./s01e07AskTheIsland";
import { carousel } from "./studio/derive";
export const s01e07Carousel = carousel("s01e07Carousel", s01e07AskTheIsland, s01e07Derive, {
  title: ["Ask the island."],
  hi: "island",
});
