// GENERATED by tools/derive-modules.mjs from s01e06Threads
import { s01e06Threads, s01e06Derive } from "./s01e06Threads";
import { verticalCut } from "./studio/derive";
export const s01e06Vertical = verticalCut("s01e06Vertical", s01e06Threads, s01e06Derive);
