// GENERATED by tools/derive-modules.mjs from s01e01Arrival
import { s01e01Arrival, s01e01Derive } from "./s01e01Arrival";
import { verticalCut } from "./studio/derive";
export const s01e01Vertical = verticalCut("s01e01Vertical", s01e01Arrival, s01e01Derive);
