// GENERATED by tools/derive-modules.mjs from s01e02PlainWords
import { s01e02PlainWords, s01e02Derive } from "./s01e02PlainWords";
import { single } from "./studio/derive";
export const s01e02Single = single("s01e02Single", s01e02PlainWords, s01e02Derive);
