// GENERATED by tools/derive-modules.mjs from s01e02PlainWords
import { s01e02PlainWords, s01e02Derive } from "./s01e02PlainWords";
import { verticalCut } from "./studio/derive";
export const s01e02Vertical = verticalCut("s01e02Vertical", s01e02PlainWords, s01e02Derive);
