#!/usr/bin/env python3
"""Import Rotli's canonical quokka line art as path DATA (geometry, not assets).

SVG poses are read verbatim. Concept poses that only exist as raster sources are
thresholded to their ink and traced with potrace. Output: src/canvas-core/quokka/poses.ts
"""
import json, os, re, subprocess, tempfile
from PIL import Image

ROTLI = "~/rotli/src/assets/characters"
OUT = "~/rotli/marketing/quokka-film/src/canvas-core/quokka/poses.ts"
SVG_POSES = ["base", "waving", "notes", "celebrating", "ai_chat", "searching", "knowledge_system",
             "stays_local", "inbox", "rest", "_logo"]
RASTER_POSES = ["walking", "thoughtful", "listening", "attention"]

def read_svg(path):
    s = open(path).read()
    vb = [float(v) for v in re.search(r'viewBox="([^"]+)"', s).group(1).split()]
    tf = re.search(r'transform="translate\(([-\d.]+),([-\d.]+)\) scale\(([-\d.]+),([-\d.]+)\)"', s)
    rule = "evenodd" if 'fill-rule="evenodd"' in s else "nonzero"
    ds = [re.sub(r"\s+", " ", d).strip() for d in re.findall(r'<path[^>]*\sd="([^"]+)"', s, re.S)]
    return {"vb": vb[2], "tf": [float(g) for g in tf.groups()] if tf else None, "rule": rule, "d": ds}

def trace(png):
    im = Image.open(png).convert("RGBA")
    w, h = im.size
    px = im.load()
    bw = Image.new("1", (w, h), 1)
    out = bw.load()
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a > 128 and (r * 0.3 + g * 0.59 + b * 0.11) < 95:
                out[x, y] = 0
    with tempfile.TemporaryDirectory() as tmp:
        bmp, svg = os.path.join(tmp, "i.bmp"), os.path.join(tmp, "o.svg")
        bw.save(bmp)
        subprocess.run(["potrace", bmp, "-s", "-o", svg, "-t", "6", "-a", "1.0", "-O", "0.3"], check=True)
        pose = read_svg(svg)
    pose["vb"] = float(w)
    return pose

poses = {n: read_svg(f"{ROTLI}/{n}.svg") for n in SVG_POSES}
for n in RASTER_POSES:
    poses[n] = trace(f"{ROTLI}/concepts/source/{n}.png")
for n, p in poses.items():
    print(f"{n:18} vb {p['vb']:.0f} tf {p['tf'] is not None} rule {p['rule']} paths {len(p['d'])} chars {sum(len(d) for d in p['d'])}")
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("// GENERATED by tools/import-quokka.py from ~/rotli/src/assets/characters. Do not edit.\n")
    f.write("// Rotli's canonical quokka line art as path geometry: vb = square viewBox side,\n")
    f.write("// tf = potrace [tx, ty, sx, sy] transform or null, rule = fill rule.\n")
    f.write("export type PoseData = { vb: number; tf: [number, number, number, number] | null; rule: CanvasFillRule; d: string[] };\n")
    f.write("export const POSES = " + json.dumps(poses) + " as unknown as Record<PoseName, PoseData>;\n")
    f.write("export type PoseName = " + " | ".join(json.dumps(n) for n in poses) + ";\n")
print("wrote", OUT, os.path.getsize(OUT), "bytes")
