// Writes the three derivative modules (+ host pages) for an episode:  node tools/derive-modules.mjs ep01Write "Write in Markdown.|See it rendered." rendered
import { writeFileSync } from "node:fs";
const [ep, cover, hi] = process.argv.slice(2), base = ep.replace(/^(ep\d+|s\d+e\d+).*/, "$1"), title = JSON.stringify(cover.split("|"));
const mods = {
  [`${base}Vertical`]: `import { ${ep}, ${base}Derive } from "./${ep}";\nimport { verticalCut } from "./studio/derive";\nexport const ${base}Vertical = verticalCut("${base}Vertical", ${ep}, ${base}Derive);\n`,
  [`${base}Carousel`]: `import { ${ep}, ${base}Derive } from "./${ep}";\nimport { carousel } from "./studio/derive";\nexport const ${base}Carousel = carousel("${base}Carousel", ${ep}, ${base}Derive, { title: ${title}, hi: ${JSON.stringify(hi ?? "")} });\n`,
  [`${base}Single`]: `import { ${ep}, ${base}Derive } from "./${ep}";\nimport { single } from "./studio/derive";\nexport const ${base}Single = single("${base}Single", ${ep}, ${base}Derive);\n`,
};
for (const [id, src] of Object.entries(mods)) { writeFileSync(`src/canvas-core/${id}.ts`, `// GENERATED by tools/derive-modules.mjs from ${ep}\n${src}`); writeFileSync(`src/hosts/page-${id}.ts`, `import { ${id} } from "../canvas-core/${id}";\nimport { mountFilm } from "./page";\nmountFilm(${id});\n`); console.log(id); }
