// THUMBNAILS: the designed poster of every Rotli video, drawn in code from the piece's own frames
// (src/canvas-core/thumbnails.ts) with the per-piece choices in brand/thumbnails.json: which frame, the focus point
// and zoom, the title, its key word and the series label. Landscape pieces get 1280×720 (YouTube), vertical ones a
// 1080×1920 cover (Reels, Shorts, TikTok).
//   node tools/thumbnails.mjs                 draw every thumbnail -> out/thumbnails/<slug>.jpg, re-record the golden
//   node tools/thumbnails.mjs --only <slug>   draw one (and re-record only its hash), for iterating on a pick
//   node tools/thumbnails.mjs --check         draw and compare with golden/thumbnails.json (writes nothing); exit 1 on
//                                             a difference, or when a Rotli video has no thumbnail
// Each thumbnail is its own generated page (.tmp/thumbnails/): the source piece's module is bundled alone, exactly as
// in its own render, so its theme family and assets are its own. Every frame is drawn twice and must reproduce. The
// golden holds the sha256 of each PNG (pixels); the JPG beside it is made from that PNG by ffmpeg.
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { buildPage } from "./build-page.mjs";
import { detect } from "./detect.mjs";
import * as playwright from "./adapters/playwright.mjs";

process.chdir(new URL("..", import.meta.url).pathname); // runs from the root or from motion/

const DATA = resolve("brand/thumbnails.json"),
  GOLDEN = resolve("golden/thumbnails.json"),
  OUT = resolve("out/thumbnails"),
  TMP = resolve(".tmp/thumbnails");
const die = (m) => {
  console.error(`thumbnails: ${m}`);
  process.exit(1);
};
const args = process.argv.slice(2),
  check = args.includes("--check"),
  onlyAt = args.indexOf("--only"),
  only = onlyAt >= 0 ? (args[onlyAt + 1] ?? die("--only needs a slug")) : null;
const unknown = args.filter((a, i) => a !== "--check" && a !== "--only" && !(onlyAt >= 0 && i === onlyAt + 1));
if (unknown.length) die(`unknown argument ${unknown[0]}`);

const read = (p) => JSON.parse(readFileSync(p, "utf8"));
const pieces = read("pieces.json").pieces,
  byId = new Map(pieces.map((p) => [p.id, p])),
  specs = read(DATA).thumbnails;
// a Rotli video = every video that is not a study (studies name their pieces in their briefs)
const studyIds = new Set(
  readdirSync("series/studies/briefs")
    .filter((f) => f.endsWith(".json"))
    .flatMap((f) => Object.values(read(`series/studies/briefs/${f}`).pieces ?? {})),
);
const rotliVideos = pieces.filter((p) => p.kind === "video" && !studyIds.has(p.id));
const moduleOf = (id) => {
  const host = `src/hosts/page-${id}.ts`;
  if (!existsSync(host)) die(`${id} has no host page (${host})`);
  const m = readFileSync(host, "utf8").match(/from "\.\.\/canvas-core\/([\w/]+)"/);
  return m ? m[1] : die(`${host} imports no canvas-core module`);
};

// the data must cover every Rotli video, once, and name only registered pieces
const seen = new Set();
for (const s of specs) {
  const p = byId.get(s.piece) ?? die(`${s.piece} is not in pieces.json`);
  if (p.kind !== "video" || studyIds.has(p.id)) die(`${s.piece} is not a Rotli video`);
  if (seen.has(s.piece)) die(`${s.piece} has two thumbnails`);
  if (s.source && !byId.has(s.source)) die(`${s.piece}: source ${s.source} is not in pieces.json`);
  seen.add(s.piece);
}
const missing = rotliVideos.filter((p) => !seen.has(p.id)).map((p) => p.id);
if (missing.length) die(`no thumbnail for ${missing.join(", ")} (add them to brand/thumbnails.json)`);
const slugOf = (s) => byId.get(s.piece).slug;
const todo = only ? specs.filter((s) => slugOf(s) === only) : specs;
if (!todo.length) die(`no thumbnail with slug ${only}`);

const golden = existsSync(GOLDEN) ? read(GOLDEN) : {};
if (check && !Object.keys(golden).length) die("no golden/thumbnails.json to check against: run without --check first");
const env = detect();
if (!env.pw.ok || !env.browser.ok) die(`no browser to draw in: ${env.report.playwright} / ${env.report.browser}`);
if (!check && !env.ffmpeg.ok) die(`ffmpeg is needed to write the JPGs: ${env.report.ffmpeg}`);
mkdirSync(TMP, { recursive: true });
if (!check) mkdirSync(OUT, { recursive: true });

/** one thumbnail: generate its module + host, build the page, draw frame 0 twice, hash, write the JPG */
const draw = async (s) => {
  const piece = s.piece,
    source = s.source ?? s.piece,
    mod = (id) => `../../src/canvas-core/${moduleOf(id)}`;
  const imports = [...new Set([piece, source])].map((id) => `import { ${id} } from "${mod(id)}";`).join("\n");
  writeFileSync(
    `${TMP}/thumb-${piece}.ts`,
    `// GENERATED by tools/thumbnails.mjs from brand/thumbnails.json\n${imports}\nimport { thumbnailFilm } from "../../src/canvas-core/thumbnails";\n` +
      `export const film = thumbnailFilm(${JSON.stringify(s)}, ${source}, ${piece}.meta.W > ${piece}.meta.H ? "landscape" : "vertical");\n`,
  );
  writeFileSync(
    `${TMP}/page-${piece}.ts`,
    `import { film } from "./thumb-${piece}";\nimport { mountFilm } from "../../src/hosts/page";\nmountFilm(film);\n`,
  );
  const page = await buildPage({
    entry: `${TMP}/page-${piece}.ts`,
    out: resolve(`dist/thumbnail-${piece}.html`),
    title: `thumbnail-${piece}`,
    probe: `export { film } from "./.tmp/thumbnails/thumb-${piece}";`,
  });
  rmSync(`${TMP}/thumb-${piece}.ts`);
  rmSync(`${TMP}/page-${piece}.ts`); // the page is self-contained: the generated sources are not kept
  const session = await playwright.open(env, page.out, { scale: 1, workers: 1 });
  try {
    const a = await session.frame(0, 0),
      b = await session.frame(0, 0);
    const sha = createHash("sha256").update(a.png).digest("hex");
    if (sha !== createHash("sha256").update(b.png).digest("hex")) die(`${piece}: NOT REPRODUCIBLE`);
    if (!check)
      execFileSync(
        env.ffmpeg.bin,
        [
          "-y",
          "-loglevel",
          "error",
          "-f",
          "png_pipe",
          "-i",
          "-",
          "-pix_fmt",
          "yuvj444p",
          "-q:v",
          "3",
          `${OUT}/${slugOf(s)}.jpg`,
        ],
        { input: a.png },
      );
    return { slug: slugOf(s), sha, meta: page.meta };
  } finally {
    await session.close();
  }
};

// four pages at a time (each is its own browser; the film is CPU-rastered, so parallel pages draw alike)
const results = [];
let next = 0;
await Promise.all(
  Array.from({ length: Math.min(4, todo.length) }, async () => {
    while (next < todo.length) {
      const s = todo[next++],
        r = await draw(s);
      results.push(r);
      const was = golden[r.slug];
      console.log(
        `  ${r.slug.padEnd(36)} ${r.meta.W}×${r.meta.H}  ${check ? (was === r.sha ? "SAME" : was ? "CHANGED" : "NEW") : `-> out/thumbnails/${r.slug}.jpg`}`,
      );
    }
  }),
);
const hashes = Object.fromEntries(results.map((r) => [r.slug, r.sha]));
if (check) {
  const drift = results.filter((r) => golden[r.slug] !== r.sha).length,
    gone = only ? [] : Object.keys(golden).filter((k) => !(k in hashes));
  for (const k of gone) console.log(`  ${k} GONE`);
  console.log(
    drift + gone.length
      ? `thumbnails: ${drift + gone.length} changed since golden`
      : `thumbnails: all ${results.length} SAME`,
  );
  process.exit(drift + gone.length ? 1 : 0);
}
// a full run owns the folder: drop JPGs of thumbnails that no longer exist
if (!only)
  for (const f of readdirSync(OUT)) if (f.endsWith(".jpg") && !(f.slice(0, -4) in hashes)) rmSync(`${OUT}/${f}`);
const record = only ? { ...golden, ...hashes } : hashes;
const ordered = Object.fromEntries(
  specs
    .map(slugOf)
    .filter((k) => k in record)
    .map((k) => [k, record[k]]),
);
writeFileSync(GOLDEN, JSON.stringify(ordered, null, 1) + "\n");
console.log(`thumbnails: ${results.length} drawn -> out/thumbnails/, golden/thumbnails.json recorded`);
